### ISSUE TITLE
TypeError: Cannot read property 'sid' of null

### ISSUE THREAD

**Issue by brandonros** [IBM-Cloud/phonebot#16]
```
2015-11-27T16:30:16.575-0500[App/0]ERR at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
2015-11-27T16:30:16.575-0500[App/0]ERR at Layer.handle [as handle_request] (/home/vcap/app/node_modules/express/lib/router/layer.js:95:5)
2015-11-27T16:30:16.575-0500[App/0]ERR at /home/vcap/app/node_modules/express/lib/router/index.js:277:22
2015-11-27T16:30:16.575-0500[App/0]ERR at PhoneBot.phone_message (/home/vcap/app/lib/phonebot.js:170:29)
2015-11-27T16:30:16.575-0500[App/0]ERRTypeError: Cannot read property 'sid' of null
2015-11-27T16:30:16.575-0500[App/0]ERR at CallManager.is_message_valid (/home/vcap/app/lib/call_manager.js:186:58)
2015-11-27T16:30:16.575-0500[App/0]ERR at /home/vcap/app/routes/index.js:42:18
2015-11-27T16:30:16.575-0500[App/0]ERR at CallManager.process (/home/vcap/app/lib/call_manager.js:149:29)
2015-11-27T16:30:16.575-0500[App/0]ERR at Route.dispatch (/home/vcap/app/node_modules/express/lib/router/route.js:112:3)
2015-11-27T16:30:16.575-0500[App/0]ERR at next (/home/vcap/app/node_modules/express/lib/router/route.js:131:13)
2015-11-27T16:30:16.575-0500[App/0]ERR at CallManager.update_call_status (/home/vcap/app/lib/call_manager.js:44:13)
```

Took forever and a day to configure. Super annoying how Bluemix won't let you update credentials. Would be much cooler of a package without the Bluemix dependency.

Did @phonebot call verified_twilio_number, got the Twilio trial message, pressed a number to start the call, and it says "An application error has occurred" and that's in the stack.

**Comment by brandonros** [comment]
I had 2 instances running on accident. Sorry!

Translation quality was 4/10 with pretty serious delay for anybody interested!
